package ru.dubograev.tests;

import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;
import ru.dubograev.helpers.DriverUtils;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;

@Tag("UI")
public class MainPageTests extends TestBase {

    private final static String EXPECTED_TITLE = "Заказать тестирование программного обеспечения. " +
            "Стоимость услуг по тестированию в агентстве Qualitica";

    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("проверка")
    void generatedTest() {
        step("Open http://google.com", () -> {
            step("// todo: just add selenium action");
        });

        step("1. Find money", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://qualitica.ru/'", () ->
                open("https://qualitica.ru/"));

        step("Page title should have text " + EXPECTED_TITLE, () -> {
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(EXPECTED_TITLE);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://qualitica.ru/'", () ->
                open("https://qualitica.ru/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}